server:
  servlet:
    context-path: /
    encoding:
      forceResponse: true
      forceRequest: true
      charset: UTF-8
      enabled: true
spring:
  security.oauth2.client.registration:
    google:
      client-id: 683041909788-msu8mt9bt6p3otjslfium3oioio5o5n2.apps.googleusercontent.com
      client-secret: sx_s7bp97SDmODrw6UJSxmL4
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/achievements
    username: postgres
    password: postgres

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: info
n2o:
  api:
    button:
      disable_on_empty_model: false
  i18n:
    default-locale: ru
  header.id: achievements
  config:
    monitoring:
      enabled: true


